version: '3.4'

services:
  webserver:
    image: nginx:1.22.1
    container_name: webserver
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx-conf:/etc/nginx/conf.d
    depends_on:
      - bship

  bship:
    image: bship
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
